
BEGIN;

DROP TABLE IF EXISTS 
"customer",
"order"
"delivery_zone",
"delivery_price",
"product",
"order_has_product"

CREATE TABLE IF NOT EXISTS "customer" (
   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   "lastname" TEXT NOT NULL,
   "firstname" TEXT NOT NULL,
   "address_1" TEXT NOT NULL,
   "address_2" TEXT,
   "zipcode" INTEGER NOT NULL,
   "city" TEXT NOT NULL,
   "email" TEXT NOT NULL UNIQUE,
   "password" TEXT NOT NULL, 
   "order_id" INTEGER NOT NULL, 
   "delivery_zone_id" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "order" (
   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   "order_number" INTEGER NOT NULL,
   "order_total" DECIMAL NOT NULL,
   "customer_id" INTEGER NOT NULL,
   "product_has_order_id" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "delivery_zone" (
   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   "zipcode" INTEGER NOT NULL,
   "city" TEXT NOT NULL,
   "delivery_price_id" INTEGER NOT NULL,
);

CREATE TABLE IF NOT EXISTS "delivery_price" (
   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   "price" DECIMAL NOT NULL,
   "zone" INTEGER NOT NULL,
);

CREATE TABLE IF NOT EXISTS "product" (
   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   "name" TEXT NOT NULL,
   "description" TEXT NOT NULL,
   "price" DECIMAL NOT NULL,
   "image" TEXT NOT NULL,
);

CREATE TABLE IF NOT EXISTS "order_has_product" (
   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   "order_id" INTEGER NOT NULL,
   "product_id" INTEGER NOT NULL
)

ALTER TABLE "customer" ADD FOREIGN KEY ("order_id") REFERENCES "order"("id"),
ALTER TABLE "customer" ADD FOREIGN KEY ("delivery_zone_id") REFERENCES "delivery_zone" ("id");
/* VERIFIER LA TABLE DE LIAISON SI REALISABLE OU PAS, UNE COMMANDE PEUT PLUSIEURS PRODUCT  */
ALTER TABLE "order" ADD FOREIGN KEY ("order_has_product_id") REFERENCES "product" ("id");
ALTER TABLE "order" ADD FOREIGN KEY ("customer_id") REFERENCES "customer" ("id");
ALTER TABLE "delivery_zone" ADD FOREIGN KEY ("delivery_price_id") REFERENCES "delivery_price" ("id");
ALTER TABLE "order_has_product" ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id");
ALTER TABLE "order_has_product" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id");


COMMIT;